spring:
  application:
    name: bff-agendador

usuario:
  url: "${USUARIO_URL:localhost:8080}"

tarefa:
  url: "${TAREFA_URL:localhost:8081}"

email:
  url: "${EMAIL_URL:localhost:8085}"

cron:
  horario: 0 0/5 6-22 ? * MON-FRI
  #  0 → no segundo zero
  #  0/5 → a cada 5 minutos
  #  6-22 → das 06h às 22h
  #  ? → Ignora o dia do mês e foda no dia da semana.
  #  * → qualquer mês
  #  MON-FRI ou 1-5 → segunda a sexta

login:
  email: admin@admin.com
  senha: 1234